<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-27T18:59:45 EET" name="Default suite" finished-at="2022-12-27T19:00:00 EET" duration-ms="15336">
    <groups>
      <group name="Automation">
        <method signature="Test_Cases.Test_The_Existance_Of_The_User_Name()[pri:0, instance:Test_Cases@4567f35d]" name="Test_The_Existance_Of_The_User_Name" class="Test_Cases"/>
        <method signature="Test_Cases.Test_The_Log_Out_Process()[pri:0, instance:Test_Cases@4567f35d]" name="Test_The_Log_Out_Process" class="Test_Cases"/>
      </group> <!-- Automation -->
    </groups>
    <test started-at="2022-12-27T18:59:45 EET" name="Default test" finished-at="2022-12-27T19:00:00 EET" duration-ms="15336">
      <class name="Test_Cases">
        <test-method is-config="true" signature="Login()[pri:0, instance:Test_Cases@4567f35d]" started-at="2022-12-27T18:59:45 EET" name="Login" finished-at="2022-12-27T19:00:00 EET" duration-ms="15081" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="Test_The_Existance_Of_The_User_Name()[pri:0, instance:Test_Cases@4567f35d]" started-at="2022-12-27T19:00:00 EET" name="Test_The_Existance_Of_The_User_Name" finished-at="2022-12-27T19:00:00 EET" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_The_Existance_Of_The_User_Name -->
        <test-method signature="Test_The_Log_Out_Process()[pri:0, instance:Test_Cases@4567f35d]" started-at="2022-12-27T19:00:00 EET" name="Test_The_Log_Out_Process" finished-at="2022-12-27T19:00:00 EET" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_The_Log_Out_Process -->
        <test-method signature="Test_The_Title()[pri:0, instance:Test_Cases@4567f35d]" started-at="2022-12-27T19:00:00 EET" name="Test_The_Title" finished-at="2022-12-27T19:00:00 EET" duration-ms="70" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GitHub] but found [Sign in to GitHub · GitHub]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GitHub] but found [Sign in to GitHub · GitHub]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test_Cases.Test_The_Title(Test_Cases.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_The_Title -->
      </class> <!-- Test_Cases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
